services:
  server:
    build:
      context: ./
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    restart: always
    user: mysql
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - POSTGRES_DB=test_mysql
      - POSTGRES_PASSWORD=password 
    expose:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    
  cache:
    image: redis
    restart: always
    expose:
      - 6379:6397
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  db-data:



